name: chatterbot_example
channels:
  - defaults
dependencies:
  - pip==21.2.4
  - python==3.9.12
  - chatterbot==1.0.8
  - chatterbot-corpus
  - python-dateutil
  - pip:
    - markupsafe==2.1.1
    - spacy==3.2.4
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.2
    - sqlalchemy==1.3.24
    - streamlit==1.8.1
    - streamlit-chat==0.0.1
    - torch==1.11.0
    - transformers
    - typer==0.4.1
    - typing-extensions==3.10.0.2
