name: chatterbot_example
channels:
  - defaults
dependencies:
  - pip==21.2.2
  - python
  - pip:
    - chatterbot
    - chatterbot-corpus==1.2.0
    - markupsafe==2.1.1
    - spacy==2.3.5
    - sqlalchemy
    - streamlit==1.8.1
    - streamlit-chat==0.0.1
    - torch==1.11.0
    - transformers
    - typer==0.4.1
    - typing-extensions
