name: chatterbot_example
channels:
  - defaults
dependencies:
  - pip
  - python
  - python-dateutil
  - pip:
    - chatterbot==1.0.4
    - chatterbot-corpus==1.2.0
    - markupsafe==2.1.1
    - spacy==3.2.4
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.2
    - sqlalchemy
    - streamlit==1.8.1
    - streamlit-chat==0.0.1
    - torch==1.11.0
    - transformers
    - typer==0.4.1
    - typing-extensions==3.10.0.2
